### ISSUE TITLE
tag rename insue

### ISSUE THREAD

**Issue by kevinsrm** [TECHNOBOT-OP/acode-autorenametag#1]
tag rename is working only in html and css it's not working in javaScript!

**Comment by TECHNOBOT-OP** [comment]
Which type of tag u try to rename in css?? And second thing in javascript when you rename open tag it automatically renamed the corresponding closing tag as you can see [here](https://t.me/AcodePlugins/2)

If you still face issue then tell me your Acode version code and check logs
